In [7]:
import numpy as np 

In [8]:
import random

In [9]:
 arr = np.random.randint(1,5, size= (4,4))

In [10]:
arr

array([[4, 1, 3, 1],
       [3, 4, 3, 4],
       [1, 2, 4, 4],
       [2, 4, 4, 1]])

### Using Reshape Function

In [11]:
arr.reshape(2,8)  # Reshaping the dimension using reshape function

array([[4, 1, 3, 1, 3, 4, 3, 4],
       [1, 2, 4, 4, 2, 4, 4, 1]])

### You can use -1 value instead of giving second value of dimension for example - [arr.reshape(2,-1)]

In [12]:
arr.reshape(2,-1)

array([[4, 1, 3, 1, 3, 4, 3, 4],
       [1, 2, 4, 4, 2, 4, 4, 1]])

### After Reshaping the array if you want to see original array then use (.base)  - [arr.reshape(16,).base]

In [17]:
arr.reshape(16,).base

array([[4, 1, 3, 1],
       [3, 4, 3, 4],
       [1, 2, 4, 4],
       [2, 4, 4, 1]])