In [24]:
import numpy as np 

### 1.Creating 1-D array

In [25]:
arr = np.array([1,2,3,4,5])

In [26]:
arr.ndim # - Checking dimension of array

1

In [27]:
arr

array([1, 2, 3, 4, 5])

In [28]:
arr.shape

(5,)

### 2.Creating 2-D array

In [29]:
arr2 = np.array([[2,3],[4,5]])

In [30]:
arr.ndim # Checking dimension of array

1

In [31]:
arr2

array([[2, 3],
       [4, 5]])

In [32]:
arr2.shape

(2, 2)

### 3.Creating 3-D array

In [33]:
arr3 = np.zeros((1,3,4))   # [3-Rows,4-Columns and 1-Extra dimension]

In [34]:
arr3.ndim

3

In [35]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
arr3.shape  # Checking shape of array

(1, 3, 4)

### 4.Dimension Remains same but unit is changed (2,3,4)

In [37]:
arr3b = np.zeros((2,3,4)) # Dimension remains same but 2 value change the unit of array and they repeating twice

In [38]:
arr3b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
arr3b.shape

(2, 3, 4)

### 5.Creating random array and filtering the value inside array

In [40]:
import random

In [43]:
arr4= np.random.randint(1,10,(5,5))

In [44]:
arr4

array([[5, 3, 8, 3, 9],
       [4, 8, 9, 5, 1],
       [2, 8, 2, 1, 2],
       [7, 2, 1, 3, 7],
       [8, 6, 7, 1, 8]])

### 6.Checking were arr4 > 5 

In [45]:
arr4 > 5

array([[False, False,  True, False,  True],
       [False,  True,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True],
       [ True,  True,  True, False,  True]])

### 7.Getting all array value whose value is grater than 5  (arr4>5)

In [55]:
arr4[arr4>5]  # Getting all values are grater than 5

array([8, 9, 8, 9, 8, 7, 7, 8, 6, 7, 8])

In [58]:
# arr4 values putting in new arrray
arr5 = arr4[arr4>5]
arr5

array([8, 9, 8, 9, 8, 7, 7, 8, 6, 7, 8])

#### 7-b.Getting all value lesser than 5

In [52]:
arr6 = arr4[arr4 < 5]

In [53]:
arr6

array([3, 3, 4, 1, 2, 2, 1, 2, 2, 1, 3, 1])