In [12]:
import numpy as np 

In [13]:
arr1 = np.random.randint(1,10,(6,6))

In [14]:
arr1

array([[3, 5, 3, 4, 8, 4],
       [8, 4, 7, 2, 8, 6],
       [3, 9, 2, 7, 9, 2],
       [1, 6, 9, 3, 6, 7],
       [6, 7, 6, 6, 9, 5],
       [1, 7, 3, 2, 4, 2]])

### 1.Accessing element inside array

In [15]:
arr1[0]

array([3, 5, 3, 4, 8, 4])

### 2.Accessing element with given values

In [16]:
arr1[0,[0,4]]

array([3, 8])

### 3. Getting value from 2 to 5 rows

In [17]:
arr1[2:5] # All element from 2nd row to 5th rows

array([[3, 9, 2, 7, 9, 2],
       [1, 6, 9, 3, 6, 7],
       [6, 7, 6, 6, 9, 5]])

### 4. Getting value from 2 to 5 rows and 0 to 2 Columns

In [18]:
arr1[2:5,0:2] # (Slicing) getting value from [2 to 5 Rows] and [0 to 2nd columns]

array([[3, 9],
       [1, 6],
       [6, 7]])

### Accessing element with r,c position

In [20]:
arr1[5,3]

2