In [3]:
import numpy as np

In [6]:
arr1 = np.random.randint(1,10,(3,3))
arr2 = np.random.randint(1,6,(3,3))

In [8]:
arr1

array([[2, 1, 3],
       [3, 8, 7],
       [9, 6, 2]])

In [9]:
arr2

array([[4, 4, 2],
       [1, 3, 1],
       [4, 3, 3]])

1.Adding

In [10]:
arr1+arr2

array([[ 6,  5,  5],
       [ 4, 11,  8],
       [13,  9,  5]])

2.Sub

In [11]:
arr1-arr2

array([[-2, -3,  1],
       [ 2,  5,  6],
       [ 5,  3, -1]])

3.Multiplying

In [12]:
arr1*arr2

array([[ 8,  4,  6],
       [ 3, 24,  7],
       [36, 18,  6]])