In [1]:
import numpy as np 

In [2]:
arr1= np.random.randint(1,4,(3,3))
arr2= np.random.randint(1,5,(3,3))

In [3]:
arr1

array([[2, 2, 1],
       [3, 2, 3],
       [2, 3, 1]])

In [4]:
arr2

array([[3, 4, 2],
       [1, 2, 4],
       [3, 2, 4]])

1. Matrix multiplication formula - [row * col1,col2,col3]

In [5]:
arr1 @ arr2    # Doing matrix multiplication [@] is used to do matrix multiplication

array([[11, 14, 16],
       [20, 22, 26],
       [12, 16, 20]])