In [1]:
import numpy as np

In [4]:
arr  = np.zeros((3,3))

In [5]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

1. Doing BroadCasting 

In [6]:
# Broadcasting by 5 in arr
arr+5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [7]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2.(i)-----> Creating 1-D & 2-D Array

In [10]:
arr1 = np.array([1,2,3,4])  # 1-D Array
arr2 = np.zeros((3,4))     # 2-D Array

In [11]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr1

array([1, 2, 3, 4])

2.(ii) -----> BraoadCasting 1-D array with 2-D array

In [13]:
arr2 + arr1

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])