In [2]:
import numpy as np

CREATING 2-D ARRAY  (because Transpose function not working in 1-D array)

In [18]:
a = np.array([[1,2,3,4]])

CHECKING DIMENSIoN oF ARRAY

In [19]:
np.ndim(a)

2

1. Doing transpose of array 'a' ---  [ T - STAND For TRANSPoSE]

In [20]:
a.T

array([[1],
       [2],
       [3],
       [4]])

2.Creating a Zeros Array and transposing with Array(a)

In [33]:
arr = np.zeros((4,4))

In [34]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Transposing 'arr' with 'a'

In [35]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

TRANSPoSE VALUE oF ARRAY WITH CLEAR EXAMPLE

In [9]:
ARR= np.random.randint(1,10,(5,6))

In [10]:
ARR

array([[2, 9, 4, 4, 2, 2],
       [3, 2, 9, 7, 5, 2],
       [4, 3, 7, 1, 9, 8],
       [5, 5, 8, 2, 1, 9],
       [1, 2, 2, 6, 2, 9]])

TRANSPoSING NoW

In [11]:
ARR.T

array([[2, 3, 4, 5, 1],
       [9, 2, 3, 5, 2],
       [4, 9, 7, 8, 2],
       [4, 7, 1, 2, 6],
       [2, 5, 9, 1, 2],
       [2, 2, 8, 9, 9]])