In [1]:
import numpy as np 

In [6]:
arr = np.array([[3,4],[4,5]])
arr

array([[3, 4],
       [4, 5]])

Using Repeating Method

In [4]:
np.repeat(arr, 3)

array([3, 3, 3, 4, 4, 4, 4, 4, 4, 5, 5, 5])

Reshaping array

In [10]:
arr.reshape(2,-1)

array([[3, 4],
       [4, 5]])

In [11]:
np.repeat(arr,2,axis= 0)

array([[3, 4],
       [3, 4],
       [4, 5],
       [4, 5]])

In [12]:
np.repeat(arr,2,axis= 1)

array([[3, 3, 4, 4],
       [4, 4, 5, 5]])