In [1]:
import numpy as np

In [3]:
import random

In [5]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [8]:
arr1,arr2

(array([[2, 6, 8, 4],
        [7, 1, 4, 6],
        [3, 1, 1, 1]]),
 array([[7, 6, 7, 2],
        [4, 4, 1, 7],
        [3, 3, 4, 3]]))

Doing some mathematical operations [** = power of a number]

In [11]:
arr1 + arr2, arr1*arr2, arr1 ** arr2, arr1/arr2, arr1>arr2

(array([[ 9, 12, 15,  6],
        [11,  5,  5, 13],
        [ 6,  4,  5,  4]]),
 array([[14, 36, 56,  8],
        [28,  4,  4, 42],
        [ 9,  3,  4,  3]]),
 array([[    128,   46656, 2097152,      16],
        [   2401,       1,       4,  279936],
        [     27,       1,       1,       1]]),
 array([[0.28571429, 1.        , 1.14285714, 2.        ],
        [1.75      , 0.25      , 4.        , 0.85714286],
        [1.        , 0.33333333, 0.25      , 0.33333333]]),
 array([[False, False,  True,  True],
        [ True, False,  True, False],
        [False, False, False, False]]))