In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

### this function thrown error Because [Matrix must be 2-D]

In [4]:
np.matrix([[[1,2],[2,3],[4,5]]])

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[2,3],[4,5],[6,7]]])

array([[[2, 3],
        [4, 5],
        [6, 7]]])

In [ ]:
np.asanyarray([[[2,3],[5,4],[5,8]]])

array([[[2, 3],
        [5, 4],
        [5, 8]]])

### converting touple into array

In [ ]:
t = ([1,2,3],[4,5,7])
type(t)

tuple

In [ ]:
np.array(t)   #Converting touple into array

array([[1, 2, 3],
       [4, 5, 7]])