In [2]:
l = [2,3,4,5,6]

In [3]:
import numpy as np  # Import numpy

In [4]:
arr = np.array(l) # Converting list into nparray

In [5]:
arr

array([2, 3, 4, 5, 6])

In [6]:
a = arr # putting array of arr into a

In [10]:
a[0] = 1000 # Changing the value of a

### In shallow copy when we change the value of anyone then they change both

In [8]:
arr

array([1000,    3,    4,    5,    6])

In [9]:
a

array([1000,    3,    4,    5,    6])