In [1]:
import numpy as np

In [5]:
arr = np.ones((3,4))

In [6]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Adding some values  in array like (5)

In [7]:
arr+5 # Adding 5 in arr

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

### Multiplying some value in array like (*5)

In [8]:
arr*5 # Multiplying by 5 in arr

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])