In [1]:
import numpy as np  # 2005 by travis Oliphant

In [2]:
np.__version__

'1.26.4'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
l = [1,2,3,4,5]

In [5]:
# numpy have a properties that they can convert list into array

# Converting list into array
arr = np.array(l)

In [6]:
# checking dimension of array
arr.ndim

1

In [7]:
type(arr)

numpy.ndarray

In [8]:
# Adding String value in integer list ..
l1 = [1,2,3,4,5,"vaibhav"]

In [9]:
arr1 = np.array(l1)

In [10]:
# Adding single string in list that change whole data type of list ..
arr1

array(['1', '2', '3', '4', '5', 'vaibhav'], dtype='<U11')

In [11]:
type(arr)

numpy.ndarray

In [12]:
arr1.dtype

dtype('<U11')

2_D array

In [13]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [14]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2.ndim

2

In [16]:
l = [1,2,3,4]

In [18]:
np.array(l)  # This is one dimension array

array([1, 2, 3, 4])

In [29]:
mat = np.matrix(l) # Matrix function by default convert in 2-d Array

In [23]:
# Making 3_D array
arr3d = np.array([[[1,2],[3,4],[6,7]]])

In [25]:
arr3d

array([[[1, 2],
        [3, 4],
        [6, 7]]])

In [27]:
arr3d.ndim  # Checking dimension of the array

3

In [28]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [31]:
mat

matrix([[1, 2, 3, 4]])

In [32]:
np.asanyarray(mat) # They not convert matrix into array because this function cannot convert any subclass a
# and matrix is subclass of array

matrix([[1, 2, 3, 4]])

In [33]:
# you can convert matrix into array using asarray of array
np.array(mat)

array([[1, 2, 3, 4]])

In [35]:
np.asarray(mat) # converting matrix into array

array([[1, 2, 3, 4]])